---
- hosts: all
  remote_user: root
  tasks:
  - name: Create a login user
    user:
      name: amit
      password: '$6$CxzO99fa4hT2Qk5E$D8AoRiFAwR5T50MedTvdW.D7koDLWLlfKSZfskK8rvsE2y6C7IdHDXNizi.q5hvtFQGcCvFD4HgkSq1XeMzUy1'
      groups: wheel
