---
- hosts: all
  remote_user: root
  tasks:
  - name: ensure emacs-nox is at the latest version
    yum:
      name: emacs-nox
      state: latest
  - name: ensure which is at the latest version
    yum:
      name: which
      state: latest
